import esbuild from "esbuild";
import process from "process";
import { builtinModules } from 'node:module';
import { cpSync, mkdirSync } from "node:fs";

const banner =
`/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = (process.argv[2] === "production");

// Emoji PNGs are shipped as loose files next to main.js (loaded at runtime via
// app.vault.adapter.getResourcePath) instead of being inlined as base64 — inlining
// 16 MB of animated PNGs bloated main.js to ~21 MB.
function copyEmojiAssets() {
	mkdirSync("emojis", { recursive: true });
	cpSync("src/emojis", "emojis", {
		recursive: true,
		filter: (src) => !src.endsWith(".ts"),
	});
}

copyEmojiAssets();

const context = await esbuild.context({
	banner: {
		js: banner,
	},
	entryPoints: ["src/main.ts"],
	bundle: true,
	external: [
		"obsidian",
		"electron",
		"@codemirror/autocomplete",
		"@codemirror/collab",
		"@codemirror/commands",
		"@codemirror/language",
		"@codemirror/lint",
		"@codemirror/search",
		"@codemirror/state",
		"@codemirror/view",
		"@lezer/common",
		"@lezer/highlight",
		"@lezer/lr",
		...builtinModules],
	format: "cjs",
	target: "es2018",
	logLevel: "info",
	sourcemap: prod ? false : "inline",
	treeShaking: true,
	outfile: "main.js",
	minify: prod,
});

if (prod) {
	await context.rebuild();
	process.exit(0);
} else {
	await context.watch();
}
