export const BASE_FILES: [string, string][] = [
	['_agent/memory/episodes/_episodes.base', [
		'views:',
		'  - type: table',
		'    name: Tabla',
		'    filters:',
		'      and:',
		'        - file.inFolder("_agent/memory/episodes")',
		'        - file.ext != "base"',
		'    order:',
		'      - file.name',
		'      - kind',
		'      - state',
		'      - origin',
		'      - session_id',
		'      - soul',
		'      - token_cost',
		'      - created_at',
		'      - updated_at',
	].join('\n')],

	['_agent/memory/items/_memory-items.base', [
		'views:',
		'  - type: table',
		'    name: Tabla',
		'    filters:',
		'      and:',
		'        - file.inFolder("_agent/memory/items")',
		'        - file.ext != "base"',
		'    order:',
		'      - file.name',
		'      - kind',
		'      - state',
		'      - created_at',
		'      - updated_at',
		'      - origin',
		'      - memory_tier',
		'      - memory_kind',
		'      - importance',
		'      - confidence',
		'      - tags',
		'      - expires_at',
		'      - proposed_tags',
		'      - related_to',
		'      - session_id',
		'      - soul',
	].join('\n')],

	['_agent/souls/_souls.base', [
		'views:',
		'  - type: table',
		'    name: Tabla',
		'    filters:',
		'      and:',
		'        - file.inFolder("_agent/souls")',
		'        - file.ext != "base"',
		'    order:',
		'      - file.name',
		'      - emoji',
		'      - name',
		'      - kind',
		'      - loading_phrases',
		'      - origin',
		'      - created_at',
		'      - updated_at',
	].join('\n')],

	['_system/traces/_traces.base', [
		'views:',
		'  - type: table',
		'    name: Tabla',
		'    filters:',
		'      and:',
		'        - file.inFolder("_system/traces")',
		'        - file.ext != "base"',
		'    order:',
		'      - file.name',
		'      - file.ctime',
	].join('\n')],

	['_system/states/_states.base', [
		'views:',
		'  - type: table',
		'    name: Items por estado',
		'    filters:',
		'      and:',
		'        - file.inFolder("_agent/memory/items")',
		'        - file.ext != "base"',
		'    order:',
		'      - file.name',
		'      - state',
		'      - memory_kind',
		'      - importance',
		'      - expires_at',
		'      - created_at',
	].join('\n')],

	['_system/memory_kinds/_memory-kinds.base', [
		'views:',
		'  - type: table',
		'    name: Items por tipo',
		'    filters:',
		'      and:',
		'        - file.inFolder("_agent/memory/items")',
		'        - file.ext != "base"',
		'    order:',
		'      - file.name',
		'      - memory_kind',
		'      - state',
		'      - importance',
		'      - confidence',
		'      - tags',
		'      - created_at',
	].join('\n')],

	['_system/memory_tiers/_memory-tiers.base', [
		'views:',
		'  - type: table',
		'    name: Items por tier',
		'    filters:',
		'      and:',
		'        - file.inFolder("_agent/memory/items")',
		'        - file.ext != "base"',
		'    order:',
		'      - file.name',
		'      - memory_tier',
		'      - memory_kind',
		'      - state',
		'      - importance',
		'      - created_at',
	].join('\n')],

	['_system/origins/_origins.base', [
		'views:',
		'  - type: table',
		'    name: Archivos por origen',
		'    filters:',
		'      and:',
		'        - file.inFolder("_agent")',
		'        - file.ext != "base"',
		'    order:',
		'      - file.name',
		'      - origin',
		'      - kind',
		'      - state',
		'      - created_at',
	].join('\n')],

	['_system/kinds/_kinds.base', [
		'views:',
		'  - type: table',
		'    name: Archivos por kind',
		'    filters:',
		'      and:',
		'        - file.inFolder("_agent")',
		'        - file.ext != "base"',
		'    order:',
		'      - file.name',
		'      - kind',
		'      - state',
		'      - origin',
		'      - created_at',
	].join('\n')],
];
